GET http://localhost:3001/api/project
###

POST http://localhost:3001/api/project
Content-Type: application/json

{
    "title": "REST-API: American Diner Menu",
    "description": "A mocked American Diner menu with a REST-API created with NodeJS and Express. The API has 5 endpoints (2 GETs, POST, PUT and DELETE) using JSON format for transporting the data, adding new items and also fetching, updating and deleting a specific item. The client side was written with React / JavaScript.",
    "mediaId": "62e7df22d26f64e4543b42b5",
    "repo": "https://github.com/millie-wy/REST-API_American-Diner-Menu",
    "categories": ["school assignment", "individual"],
    "tags": ["REST-API", "NodeJS", "Express", "React", "JavaScript"],
    "released": "04/2022"
}

###
DELETE http://localhost:3001/api/project/62e3d0217700545e42dc0cf5
